services:
  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    restart: always
    ports:
      - 21434:11434
    volumes:
      - ./ollama_data:/root/.ollama:rw
    environment:
      - OLLAMA_HOST=0.0.0.0
      - TZ=Asia/Seoul
      - LC_ALL:en_US.UTF-8
    networks:
      myNet:
        ipv4_address: 192.168.100.10

  db:
    container_name: db
    image: mariadb:11.6.2
    restart: always
    ports: 
      - 13306:3306
    volumes:
        - ./mariadb/conf.d:/etc/mysql/conf.d:ro
        - ./mariadb/data:/var/lib/mysql:rw
        - ./mariadb/initdb.d:/docker-entrypoint-initdb.d:ro
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_PORT=3306
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=ai
      - TZ=Asia/Seoul
      - LC_ALL:en_US.UTF-8
    networks:
      myNet:
        ipv4_address: 192.168.100.20

  backend:
    container_name: backend
    image: openjdk:21-jdk
    restart: always
    depends_on:
      - db
      - ollama
    links:
      - db
      - ollama
    ports:
      - 9090:8080
    volumes:
      - ./app:/usr/local/app:ro
    environment:
      - DB_DRIVER=org.mariadb.jdbc.Driver
      - DB_URL=jdbc:mariadb://db:3306/ai
      - DB_USERNAME=root
      - DB_PASSWORD=1234
      - SESSION_TIMEOUT=60m
      - AI_HOST=http://ollama:11434/
      - AI_MODEL=llama3.2-vision:11b
      - TZ=Asia/Seoul
      - LC_ALL:en_US.UTF-8
    networks:
      myNet:
        ipv4_address: 192.168.100.30
    command: java -jar /usr/local/app/ai-1.jar

networks:
  myNet:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24
          gateway: 192.168.100.254
