server:
  port: 8080
  servlet:
    session:
      timeout: 30m

spring:
  application:
    name: ai
  profiles:
    active: dev
# ENV SETTING
  config:
    import: optional:file:env[.properties]
# database SETTING
  datasource:
    driver-class-name: ${DB_DRIVER}
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
# AI SETTING
  ai:
    ollama:
      base-url: ${AI_HOST}
      chat:
        model: ${AI_MODEL}
# file size SETTING
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

# log level SETTING
logging:
  level:
    org:
      springframework:
        web: DEBUG
      thymeleaf: DEBUG
